import { CareerItem } from "@/types";

export const CAREER: CareerItem[] = [
  {
    id: 1,
    title: "꿀 스테이 관리자 페이지 유지보수",
    period: "2022.01 ~ 2022.06",
    company: "파인원커뮤니케이션즈",
    type: "유지보수",
    description: "숙박 예약 플랫폼의 관리자 페이지 유지보수 및 개선",
    role: "운영 중인 관리자 대시보드 유지보수 담당",
    contributions: [
      "숙박 예약 플랫폼의 관리자 페이지 유지보수 및 개선 담당",
      "기존 소스코드 분석을 통해 문의/공지사항 기능 및 API 연동 로직을 개선하며, 운영 중 발생한 화면 오류를 해결",
    ],
    techStack: ["React", "JavaScript", "Redux", "Axios"],
  },
  {
    id: 2,
    title: "DMZ 다큐멘터리 영화제 웹페이지 개발",
    period: "2022.08 ~ 2022.09",
    company: "파인원커뮤니케이션즈",
    type: "단기 개발",
    description:
      "영화제 기간 동안 운영된 단기 웹 서비스로, 짧은 기간 내 빠른 개발 성과가 요구된 프로젝트",
    role: "프론트엔드 개발 (6인 규모 팀 내 기능 단위 분담)",
    contributions: [
      "영화 상세정보 페이지 및 결제 기능 개발 담당",
      "필요 기능에 적합한 라이브러리 검토·PoC 후 도입 결정",
    ],
    techStack: ["React", "JavaScript", "Redux", "Axios"],
  },
  {
    id: 3,
    title: "SK 스마트링크 사용자 웹앱 개발",
    period: "2022.11 ~ 2023.06",
    company: "파인원커뮤니케이션즈",
    type: "상용 개발",
    description: "차량 카셰어링 서비스의 기존 3개 앱을 통합·고도화한 사용자 웹앱 개발 프로젝트",
    role: "프론트엔드 기능 구현 담당",
    contributions: [
      "예약, 예약내역, 예약 변경 등 핵심 시나리오 기능 개발",
      "필요 기능에 따른 라이브러리 검토 및 PoC 진행 후 도입 (react-vant, react-range-slider)",
      "GraphQL 기반 API 연동 및 예외 케이스 대응",
      "팀 코드 리뷰 및 회고 참여",
    ],
    techStack: ["React", "JavaScript", "Redux", "GraphQL", "Apollo", "Axios"],
  },
  {
    id: 4,
    title: "SK 스마트링크 웹앱 유지보수",
    period: "2023.07 ~ 2023.12",
    company: "파인원커뮤니케이션즈",
    type: "유지보수",
    description: "운영 중인 카셰어링 웹앱의 안정성 확보와 품질 개선을 위한 유지보수 프로젝트",
    role: "유지보수 전담 프론트엔드 개발자",
    contributions: [
      "고객사 요청에 따른 기능 수정 및 버그 패치",
      "기존 코드 이해 기반의 리팩토링 및 개선 작업",
    ],
    techStack: ["React", "JavaScript", "Redux", "GraphQL", "Apollo", "Axios"],
  },
  {
    id: 5,
    title: "SK 스마트링크 웹앱 고도화",
    period: "2024.01 ~ 2024.06",
    company: "파인원커뮤니케이션즈",
    type: "기능 개선",
    description:
      "카셰어링 웹앱의 페이즈2 개발로, 고객사별 요구사항을 반영한 기능 확장 및 커스터마이징 프로젝트",
    role: "프론트엔드 기능 개발 및 커스터마이징 담당",
    contributions: [
      "쿠폰 기능 및 고객사 전용 기능 등 맞춤형 확장 기능 개발",
      "외부 기획자·디자이너와 협업하여 UI/UX 개선 및 보완",
    ],
    techStack: ["React", "JavaScript", "Redux", "GraphQL", "Apollo", "Axios"],
  },
  {
    id: 6,
    title: "Z-GRC 보안 인증 지원 솔루션 (MVP)",
    period: "2024.09 ~ 2024.10",
    company: "ZIEN",
    type: "MVP",
    description:
      "2024 ISEC 보안 전시회 출품을 목표로, IoT 보안 인증 체크리스트 기반으로 2개월 만에 구축한 웹앱 MVP",
    role: "퍼블리싱 및 프론트엔드 개발, 배포 담당",
    contributions: [
      "Next.js + TypeScript 기반 프로젝트 구조 설계 및 초기 세팅",
      "TailwindCSS 활용한 퍼블리싱 및 반응형 UI 구현",
      "보안 체크리스트 및 대응 가이드 기능 개발",
      "AWS Amplify를 통한 배포 환경 구성 및 운영",
    ],
    techStack: ["Next.js", "TypeScript", "TailwindCSS", "AWS Amplify"],
  },
  {
    id: 7,
    title: "ZIEN 회사 홈페이지 유지보수",
    period: "2024.10 ~ 현재",
    company: "ZIEN",
    type: "유지보수",
    description:
      "홍보 웹사이트, 관리자 시스템, 서버를 통합 관리하며 안정적 운영과 기능 개선을 담당",
    role: "프론트엔드 및 백엔드 유지보수, 인증서 관리, 신규 기능 추가",
    contributions: [
      "Next.js 기반 UI 개선 및 관리자 react-admin 페이지 기능 보완",
      "NestJS 서버 API 수정 및 신규 기능 개발",
      "인증서 자동화 프로세스 구축 및 HTTPS 적용",
      "Docker 기반 배포 환경 관리",
      "Cypress 기반 E2E 테스트 작성 및 GitHub Actions 연동으로 CI/CD 품질 보장",
    ],
    techStack: [
      "Next.js",
      "TypeScript",
      "NestJS",
      "React-admin",
      "TailwindCSS",
      "Docker",
      "Cypress",
      "GitHub Actions",
    ],
  },
  {
    id: 8,
    title: "Z-IoT 취약점 진단 솔루션 유지보수",
    period: "2024.10 ~ 현재",
    company: "ZIEN",
    type: "유지보수",
    description: "IoT 펌웨어 보안 진단 솔루션의 구조 분석과 기능 개선 및 안정적 배포 관리",
    role: "프론트엔드 구조 분석 및 기능 개선, 배포 관리",
    contributions: [
      "기존 코드 구조 분석 및 기능 개선",
      "진단 결과 시각화 UI 및 가이드 제공 기능 개선",
      "AWS EC2 컨테이너 기반 배포 환경 운영 및 안정화",
      "Cypress 기반 E2E 테스트 작성 및 GitHub Actions 연동으로 CI/CD 안정성 확보",
    ],
    techStack: ["Next.js", "TypeScript", "TailwindCSS", "AWS EC2", "Cypress", "GitHub Actions"],
  },
  {
    id: 9,
    title: "Z-ONE 보안 컨설팅 솔루션 마이그레이션",
    period: "2024.11 ~ 2025.06",
    company: "ZIEN",
    type: "마이그레이션",
    description:
      "특정 고객사 전용으로 구축된 보안 컨설팅 솔루션을 범용 솔루션으로 확장하기 위해, Vue/Spring 기반을 Next.js/Django로 전환하는 마이그레이션 프로젝트",
    role: "프론트엔드 마이그레이션 및 프로젝트 관리(PM)",
    contributions: [
      "고객사 전용 도메인·API 의존성 제거 및 다수 고객사 활용 가능하도록 구조 개편",
      "Vue.js → Next.js 전환을 통한 프론트엔드 마이그레이션 수행",
      "프리랜서 백엔드(Django) 개발 관리 및 API 연동 테스트",
      "Figma 기반 기획 및 UI 설계 진행",
    ],
    techStack: ["Next.js", "TypeScript", "TailwindCSS", "Figma", "Vue.js", "Django", "Spring"],
  },
  {
    id: 10,
    title: "Z-Sentinel 네트워크 취약점 분석 솔루션 (MVP)",
    period: "2025.02 ~ 2025.03",
    company: "ZIEN",
    type: "MVP",
    description:
      "2025 SECON 출품용으로 개발한 온프레미스 네트워크 보안 솔루션 MVP — AI 기반 이상징후 탐지와 네트워크 장치 자동 식별·관리 기능을 포함",
    role: "프론트엔드 구조 설계, 시각화 POC 및 단독 프론트엔드 개발·배포 담당",
    contributions: [
      "Figma 기반 UI 설계 및 Tailwind로 퍼블리싱·반응형 구현",
      "대시보드의 토폴로지(Topology) 및 그래프 시각화 POC 설계·구현",
      "10만 건 이상 대용량 데이터 렌더링 성능 검증 및 최적화 작업 수행",
      "온프레미스 특성(데이터 프라이버시)을 고려한 배포·운영 검토 및 AWS Amplify로 MVP 배포",
    ],
    techStack: [
      "Next.js",
      "TypeScript",
      "TailwindCSS",
      "AWS Amplify",
      "대용량 시각화(WebGL/Canvas)",
    ],
  },
  {
    id: 11,
    title: "Z-IoT 고도화 프로젝트",
    period: "2025.04 ~ 2025.06",
    company: "ZIEN",
    type: "기능 고도화",
    description: "EN/NIST 기준 대응 및 LLM 기반 대응 가이드 UI 구현",
    role: "디자인 해석, 프론트 개발 및 배포 환경 구성",
    contributions: [
      "챗봇형 인터페이스 및 LLM 응답 흐름 개발",
      "EN/NIST 대응 가이드 분기 로직 구현",
      "EC2 + Docker Compose 배포 환경 구성 및 HTTPS 적용",
    ],
    techStack: ["Next.js", "TypeScript", "TailwindCSS", "AWS EC2", "Docker Compose"],
  },
  {
    id: 12,
    title: "Z-RED 보안 체크리스트 설문 웹앱 (MVP)",
    period: "2025.06 ~ 2025.07",
    company: "ZIEN",
    type: "MVP",
    description:
      "2025년 9월부터 시행되는 유럽 RED 보안 규제 대응을 위해, 제조사 제품의 자가진단 설문을 기반으로 컨설팅을 유도하는 홍보성 웹앱",
    role: "프론트엔드 개발, 반응형 설계, 배포",
    contributions: [
      "모바일/PC 반응형 UI 퍼블리싱 및 개발 단독 수행",
      "설문 흐름과 조건 분기 로직 설계·구현",
      "Next.js 기반 정적 웹 구성 및 배포",
      "프로젝트 성과로 독일 Bureau Veritas와 MOU 체결에 기여",
    ],
    techStack: ["Next.js", "TypeScript", "TailwindCSS"],
  },
  {
    id: 13,
    title: "Z-ONE 2.0 보안 컨설팅 솔루션 고도화",
    period: "2025.07 ~ 2025.10(예정)",
    company: "ZIEN",
    type: "기능 고도화",
    description:
      "마이그레이션 완료된 Z-ONE 2.0 솔루션을 기반으로, 범용성을 높이고 신규 기능을 기획·구현하는 고도화 프로젝트",
    role: "프론트엔드/백엔드 기능 개발, 기획 및 디자인 관리",
    contributions: [
      "범용성을 고려한 신규 기능 기획 및 요구사항 정의",
      "Django 서버 기능 개발 및 Next.js 프론트엔드 기능 확장",
      "POC용 개발기 배포 환경 구축 (GCP VM 컨테이너 활용)",
      "디자인 시스템 개발을 외부에 의뢰하고, 이를 토대로 주요 페이지·모달·컴포넌트를 직접 Figma에서 설계·구현",
      "퍼블리싱 및 UI/UX 일관성 확보",
    ],
    techStack: ["Next.js", "TypeScript", "TailwindCSS", "Django", "GCP VM", "Docker", "Figma"],
  },
];
