import { CareerItem } from "@/types";

export const CAREER: CareerItem[] = [
  {
    id: 1,
    title: "꿀 스테이 관리자 페이지 유지보수",
    period: "2022.01 ~ 2022.06",
    company: "파인원커뮤니케이션즈",
    type: "유지보수",
    description: "숙박 예약 플랫폼의 관리자 페이지 유지보수 및 개선",
    role: "운영 중인 관리자 대시보드 유지보수 담당",
    contributions: [
      "기존 코드 분석 및 문의/공지사항 기능 개선",
      "API 연동 로직 개선 및 화면 오류 처리",
    ],
    techStack: ["React", "JavaScript", "Redux", "Axios"],
  },
  {
    id: 2,
    title: "DMZ 다큐멘터리 영화제 웹페이지 개발",
    period: "2022.08 ~ 2022.09",
    company: "파인원커뮤니케이션즈",
    type: "단기 개발",
    description: "영화제 기간 동안만 운영되는 단기 웹 서비스 개발",
    role: "프론트엔드 개발 (6인 규모 팀 내 기능 단위 분담)",
    contributions: [
      "영화 상세정보 페이지, 결제 관련 기능 등 주요 화면 개발",
      "요구된 기능에 따라 라이브러리 검토 및 도입 결정",
    ],
    techStack: ["React", "JavaScript", "Redux", "Axios"],
  },
  {
    id: 3,
    title: "SK 스마트링크 사용자 웹앱 개발",
    period: "2022.11 ~ 2023.06",
    company: "파인원커뮤니케이션즈",
    type: "상용 개발",
    description: "차량 카셰어링 서비스를 위한 사용자용 웹앱 개발 프로젝트",
    role: "프론트엔드 기능 구현 담당",
    contributions: [
      "예약하기, 예약내역 확인, 예약 변경 등 핵심 기능 개발",
      "라이브러리 검토 및 도입 (react-vant, react-range-slider)",
      "GraphQL 기반 API 요청/응답 처리 및 예외 케이스 대응",
      "팀 코드 리뷰 및 회고 참여",
    ],
    techStack: ["React", "JavaScript", "Redux", "GraphQL", "Apollo", "Axios"],
  },
  {
    id: 4,
    title: "SK 스마트링크 웹앱 유지보수",
    period: "2023.07 ~ 2023.12",
    company: "파인원커뮤니케이션즈",
    type: "유지보수",
    description: "운영 중인 카셰어링 웹앱의 유지보수 및 신규 요청사항 대응",
    role: "유지보수 전담 프론트엔드 개발자",
    contributions: [
      "고객사 요청에 따른 기능 수정 및 버그 패치",
      "기존 코드 이해 및 리팩토링 작업 수행",
    ],
    techStack: ["React", "JavaScript", "Redux", "GraphQL", "Apollo", "Axios"],
  },
  {
    id: 5,
    title: "SK 스마트링크 웹앱 고도화",
    period: "2024.01 ~ 2024.06",
    company: "파인원커뮤니케이션즈",
    type: "기능 개선",
    description: "기존 웹앱의 기능 개선 및 고객사별 요구사항에 맞춘 커스터마이징 프로젝트",
    role: "프론트엔드 기능 개발 및 커스터마이징 담당",
    contributions: [
      "쿠폰 기능, 고객사별 전용 기능 등 확장 기능 개발",
      "외부 기획자 및 디자이너와 협업하여 UI/UX 보완",
    ],
    techStack: ["React", "JavaScript", "Redux", "GraphQL", "Apollo", "Axios"],
  },
  {
    id: 6,
    title: "Z-GRC 보안 인증 지원 솔루션 (MVP)",
    period: "2024.09 ~ 2024.10",
    company: "ZIEN",
    type: "MVP",
    description: "ISEC 보안 전시회 출품을 위한 IoT 보안 인증 체크리스트 기반 MVP",
    role: "퍼블리싱 및 프론트엔드 개발, 배포 담당",
    contributions: [
      "Next.js 기반 프로젝트 구조 설계 및 초기 세팅",
      "TailwindCSS 기반 퍼블리싱 및 반응형 대응",
      "체크리스트 및 대응 가이드 기능 구현",
      "AWS Amplify 배포 환경 구성",
    ],
    techStack: ["Next.js", "TypeScript", "TailwindCSS", "AWS Amplify"],
  },
  {
    id: 7,
    title: "ZIEN 회사 홈페이지 유지보수",
    period: "2024.10 ~ 현재",
    company: "ZIEN",
    type: "유지보수",
    description: "회사 홍보 웹사이트 및 관리자 시스템 유지보수 및 배포 관리",
    role: "프론트엔드 및 백엔드 유지보수, 인증서 관리, 신규 기능 추가",
    contributions: [
      "Next.js 기반 UI 개선 및 관리자 react-admin 페이지 기능 수정",
      "NestJS API 수정",
      "인증서 갱신 및 HTTPS 적용",
      "Amplify 및 Docker 기반 배포 환경 관리",
    ],
    techStack: ["Next.js", "TypeScript", "NestJS", "React-admin", "TailwindCSS"],
  },
  {
    id: 8,
    title: "Z-IoT 취약점 진단 솔루션 유지보수",
    period: "2024.10 ~ 현재",
    company: "ZIEN",
    type: "유지보수",
    description: "IoT 펌웨어 보안 진단 솔루션 유지보수 및 기능 개선",
    role: "프론트엔드 구조 분석 및 기능 개선",
    contributions: [
      "기존 코드 구조 분석",
      "진단 결과 시각화 UI 및 가이드 제공 개선",
      "기능 수정 및 배포 절차 안정화",
    ],
    techStack: ["Next.js", "TypeScript", "TailwindCSS"],
  },
  {
    id: 9,
    title: "Z-ONE 보안 컨설팅 시스템 마이그레이션",
    period: "2024.11 ~ 2025.06",
    company: "ZIEN",
    type: "마이그레이션",
    description: "기존 Vue/Spring 시스템을 Next.js/Django로 전환",
    role: "프론트엔드 마이그레이션 개발 및 PM",
    contributions: [
      "기획 및 Figma 기반 UI 설계",
      "Vue → Next.js 기능 이전",
      "프리랜서 백엔드 관리 및 연동 테스트",
    ],
    techStack: ["Next.js", "TypeScript", "TailwindCSS", "Figma", "Vue.js"],
  },
  {
    id: 10,
    title: "Z-Sentinel 네트워크 취약점 분석 솔루션 (MVP)",
    period: "2025.02 ~ 2025.03",
    company: "ZIEN",
    type: "MVP",
    description: "AI 기반 이상징후 탐지를 포함한 온프레미스 보안 솔루션 MVP",
    role: "프론트엔드 구조 설계, 시각화 POC, 배포 담당",
    contributions: [
      "Figma 기반 UI 설계 및 Tailwind 퍼블리싱",
      "대시보드 Topology 및 그래프 POC",
      "10만 건 이상 대용량 렌더링 성능 검증",
      "AWS Amplify 배포",
    ],
    techStack: ["Next.js", "TypeScript", "TailwindCSS"],
  },
  {
    id: 11,
    title: "Z-IoT 고도화 프로젝트",
    period: "2025.04 ~ 2025.06",
    company: "ZIEN",
    type: "기능 고도화",
    description: "EN/NIST 기준 대응 및 LLM 기반 대응 가이드 UI 구현",
    role: "디자인 해석, 프론트 개발 및 배포 환경 구성",
    contributions: [
      "챗봇형 인터페이스 및 LLM 응답 흐름 개발",
      "EN/NIST 대응 가이드 분기 로직 구현",
      "EC2 + Docker Compose 배포 환경 구성 및 HTTPS 적용",
    ],
    techStack: [
      "Next.js",
      "TypeScript",
      "TailwindCSS",
      "Figma",
      "AWS EC2",
      "Docker Compose",
      "Route53",
    ],
  },
  {
    id: 12,
    title: "Z-RED 보안 체크리스트 설문 웹앱 (MVP)",
    period: "2025.06 ~ 2025.07",
    company: "ZIEN",
    type: "MVP",
    description: "RED 보안 자가진단 설문을 통한 컨설팅 유도 웹앱",
    role: "프론트엔드 개발, 반응형 설계, 배포",
    contributions: [
      "모바일/PC 반응형 UI 구현",
      "설문 흐름 및 조건 분기 로직 구성",
      "Next.js 기반 정적 웹 구성 및 배포",
    ],
    techStack: ["Next.js", "TypeScript", "TailwindCSS"],
  },
];
